name: 3DSC
channels:
#  - arturo.mendoza.quispe
  - conda-forge
  - defaults
dependencies:
  - ase
#  - dscribe=1.0         # Later versions renamed the variables rcut, nmax, lmax to r_cut, n_max, l_max. For DSOAP features
  - gemmi
  - joblib
#  - matplotlib
#  - matplotlib-base
  - numpy<1.24        # Later versions incompatible with pymatgen due to call of np.int which was removed in numpy 1.24
  - numpy-base
#  - openbabel
  - pandas<2          # Incompatible with pandas >=2.0 because of deprecated function pd.Dataframe.append()
  - pip
  - pymatgen=2020
  - python>=3.8.6
#  - seaborn
#  - seaborn-base
#  - scikit-learn     # for PCA of DSOAP features
  - tqdm
  - yaml
#  - chemml           # for MAGPIE features
  - pip:
    - -e .
#    - megnet         # for graph
##    - --no-deps chemml==0.8
#    - chemprop==1.3.0
#    - clang==5.0
#    - dataclasses==0.6
#    - dataclasses-json==0.5.6
#    - deprecated==1.2.13
#    - dm-tree==0.1.6
#    - et-xmlfile==1.1.0
#    - flatbuffers==1.12
#    - gast==0.4.0
#    - google-pasta==0.2.0
##    - gpflow==2.2.1
#    - h5py==3.1.0
#    - hyperopt==0.2.5
##    - keras==2.7.0
##    - keras-nightly==2.8.0.dev2021111108
##    - keras-preprocessing==1.1.2
#    - libclang==12.0.0
#    - lmdb==1.2.1
#    - marshmallow==3.14.1
#    - marshmallow-enum==1.5.1
#    - multipledispatch==0.6.0
#    - openpyxl==3.0.9
#    - opt-einsum==3.3.0
#    - pandas-flavor==0.2.0
#    - s3transfer==0.4.2
##    - tb-nightly==2.8.0a20211111
##    - tensorboardx==2.2
##    - tensorflow-macos==2.7.0
##    - tensorflow-estimator==2.7.0
##    - tensorflow-io-gcs-filesystem==0.22.0
##    - tensorflow-probability==0.14.1
#    - termcolor==1.1.0
#    - typed-argument-parser==1.6.2
#    - typing-inspect==0.6.0
#    - wget==3.2
#    - xarray==0.17.0
#    - yamldataclassconfig==1.5.0
