name: 3DSC
channels:
  - arturo.mendoza.quispe
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - absl-py=0.12.0
  - aiida-core=1.6.3
  - aiida-core.services=1.6.3
  - aio-pika=6.8.0
  - aiohttp=3.8.1
  - aiormq=3.3.1
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - aldjemy=0.9.1
  - alembic=1.4.1
  - anyio=2.2.0
  - anyjson=0.3.3
  - appdirs=1.4.4
  - apscheduler=3.7.0
  - archive-path=0.2.1
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=1.1.0
  - ase=3.20.1
  - asn1crypto=1.4.0
  - astroid=2.5
  - async-timeout=4.0.1
  - async_generator=1.10
  - atk=2.36.0
  - atk-1.0=2.36.0
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - automat=20.2.0
  - autopep8=1.5.6
  - autovizwidget=0.18.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - boost=1.72.0
  - boost-cpp=1.72.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2022.4.26
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2022.5.18.1
  - cffi=1.14.0
  - cftime=1.4.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - circus=0.17.1
  - click=7.1.2
  - click-completion=0.5.2
  - click-config-file=0.6.0
  - click-spinner=0.1.10
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - colour=0.1.5
  - conda-pack=0.6.0
  - configobj=5.0.6
  - configparser=5.0.2
  - confuse=1.4.0
  - constantly=15.1.0
  - coverage=5.5
  - cryptography=3.4.7
  - cssselect=1.1.0
  - cudatoolkit=10.2.89
  - curl=7.76.1
  - cycler=0.10.0
  - cython=0.29.23
  - databricks-cli=0.9.1
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - diff-match-patch=20200713
  - django=2.2.14
  - docker-py=4.4.1
  - docker-pycreds=0.4.0
  - docutils=0.16
  - dscribe=1.0.0
  - entrypoints=0.3
  - erlang=23.1.4
  - ete3=3.1.2
  - expat=2.2.10
  - flake8=3.9.0
  - flask=1.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.2.0
  - fsspec=2021.10.1
  - furl=2.1.0
  - future=0.18.2
  - gdk-pixbuf=2.38.2
  - gemmi=0.4.4
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.14
  - glib=2.63.1
  - gmp=6.2.1
  - gmpy2=2.0.8
  - gobject-introspection=1.66.1
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - googledrivedownloader=0.4
  - gorilla=0.4.0
  - graphite2=1.3.13
  - graphviz=2.42.3
  - greenlet=1.0.0
  - grpcio=1.38.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gtk2=2.24.32
  - gts=0.7.6
  - gunicorn=20.1.0
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - hdijupyterutils=0.18.0
  - html5lib=1.1
  - htmlmin=0.1.12
  - hyperlink=21.0.0
  - icu=64.2
  - idna=2.10
  - imagehash=4.2.0
  - imagesize=1.2.0
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - incremental=17.5.0
  - infinity=1.4
  - iniconfig=1.1.1
  - intel-openmp=2021.2.0
  - intervals=0.8.1
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=5.8.0
  - itemadapter=0.2.0
  - itemloaders=1.0.4
  - itsdangerous=1.1.0
  - jedi=0.17.1
  - jeepney=0.6.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsoncpp=1.8.4
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=1.0.0
  - keyring=22.3.0
  - kiwipy=0.7.4
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - latexcodec=2.0.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.76.1
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libllvm10=10.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libpq=13.2
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxgboost=1.4.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - libzlib=1.2.11
  - llvmlite=0.36.0
  - lxml=4.6.2
  - lz4-c=1.9.2
  - mako=1.1.4
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - missingno=0.4.2
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - mlflow=1.17.0
  - mock=4.0.3
  - monty=4.0.2
  - more-itertools=8.7.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - multidict=5.1.0
  - mypy_extensions=0.4.3
  - nb_conda_kernels=2.3.1
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - netcdf4=1.5.5.1
  - networkx=2.5.1
  - ninja=1.10.2
  - nose=1.3.7
  - notebook=6.3.0
  - numba=0.53.1
  - numpy=1.20.1
  - numpy-base=1.20.1
  - numpydoc=1.1.0
  - oauthlib=3.1.1
  - olefile=0.46
  - onnx=1.9.0
  - onnxruntime=1.7.2
  - openbabel=3.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - orderedmultidict=1.0.1
  - packaging=20.9
  - palettable=3.3.0
  - pamqp=2.3.0
  - pandas=1.2.4
  - pandas-profiling=2.9.0
  - pandoc=2.12
  - pandocfilters=1.4.3
  - pango=1.42.4
  - paramiko=2.7.2
  - parsel=1.5.2
  - parso=0.7.0
  - passlib=1.7.4
  - patsy=0.5.2
  - pcre=8.44
  - pexpect=4.8.0
  - pgsu=0.2.0
  - phik=0.11.2
  - phonenumbers=8.10.14
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.0.1
  - pixman=0.38.0
  - plotly=4.14.3
  - pluggy=0.13.1
  - plumpy=0.19.0
  - postgresql=13.2
  - prometheus_client=0.10.1
  - prometheus_flask_exporter=0.18.1
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - protego=0.1.16
  - protobuf=3.16.0
  - psutil=5.8.0
  - psycopg2=2.8.6
  - psycopg2-binary=2.8.6
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-xgboost=1.4.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11=2.7.0
  - pybind11-global=2.7.0
  - pybtex=0.23.0
  - pycairo=1.19.1
  - pycifrw=4.4.1
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydeprecate=0.3.1
  - pydispatcher=2.0.5
  - pydocstyle=6.0.0
  - pydotplus=2.0.2
  - pyflakes=2.2.0
  - pygments=2.8.1
  - pyhamcrest=2.0.2
  - pyjwt=2.1.0
  - pylint=2.7.4
  - pymatgen=2020.12.31
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=6.2.3
  - pytest-runner=5.3.0
  - python=3.8.6
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python-graphviz=0.16
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python-louvain=0.15
  - python_abi=3.8
  - pytray=0.3.1
  - pytz=2019.3
  - pyu2f=0.1.5
  - pywavelets=1.1.1
  - pyxdg=0.27
  - pyyaml=5.1.2
  - pyzmq=20.0.0
  - qdarkstyle=3.0.2
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - querystring_parser=1.2.4
  - queuelib=1.5.0
  - rabbitmq-server=3.8.15
  - rdkit=2020.09.2
  - re2=2021.04.01
  - readline=8.1
  - reentry=1.3.2
  - reportlab=3.5.67
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - retrying=1.3.3
  - rope=0.18.0
  - rsa=4.7.2
  - rtree=0.9.7
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.2
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - scrapy=2.4.1
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - secretstorage=3.3.1
  - selenium=3.141.0
  - send2trash=1.5.0
  - service_identity=18.1.0
  - setuptools=52.0.0
  - shellingham=1.4.0
  - shortuuid=1.0.1
  - sigopt=5.3.1
  - simple_slurm=0.2.2
  - simplejson=3.17.2
  - sip=4.19.13
  - six=1.15.0
  - skorch=0.10.0
  - smmap=3.0.5
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sortedcontainers=2.3.0
  - soupsieve=2.2.1
  - sparse=0.12.0
  - spglib=1.16.0
  - sphinx=3.5.4
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlalchemy=1.3.23
  - sqlalchemy-utils=0.36.8
  - sqlite=3.35.4
  - sqlparse=0.4.1
  - statsmodels=0.12.2
  - sympy=1.8
  - tabulate=0.8.9
  - tangled-up-in-unicode=0.0.7
  - tbb=2020.3
  - tensorboard=2.7.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.0.5
  - twisted=21.2.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzcode=2021a
  - tzdata=2021a
  - tzlocal=2.0.0
  - ujson=4.0.2
  - uncertainties=3.1.5
  - upf_to_json=0.9.2
  - urllib3=1.26.4
  - visions=0.5.0
  - vtk=8.2.0
  - w3lib=1.21.0
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=2.1.0
  - xgboost=1.4.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=5.3.0
  - zstd=1.4.5
  - pip:
    - arm-mango==1.1.0
    - astunparse==1.6.3
    - attrdict==2.0.1
    - biopython==1.78
    - boto3==1.17.67
    - botocore==1.20.67
    - chemml==0.8
    - chemprop==1.3.0
    - clang==5.0
    - dataclasses==0.6
    - dataclasses-json==0.5.6
    - deprecated==1.2.13
    - dm-tree==0.1.6
    - et-xmlfile==1.1.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-pasta==0.2.0
    - gpflow==2.2.1
    - h5py==3.1.0
    - hyperopt==0.2.5
    - keras==2.7.0
    - keras-nightly==2.8.0.dev2021111108
    - keras-preprocessing==1.1.2
    - libclang==12.0.0
    - lmdb==1.2.1
    - marshmallow==3.14.1
    - marshmallow-enum==1.5.1
    - megnet==1.2.9
    - multipledispatch==0.6.0
    - openpyxl==3.0.9
    - opt-einsum==3.3.0
    - pandas-flavor==0.2.0
    - s3transfer==0.4.2
    - tb-nightly==2.8.0a20211111
    - tensorboardx==2.2
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.22.0
    - tensorflow-probability==0.14.1
    - termcolor==1.1.0
    - typed-argument-parser==1.6.2
    - typing-inspect==0.6.0
    - wget==3.2
    - xarray==0.17.0
    - yamldataclassconfig==1.5.0
    - -e .
