n_epochs: 500
nn_layers: 5
nn_act: 'relu'
nn_base_dim: 100
nn_end_dim: 30
nn_patience: 100
nn_batch_size: 32
nn_solver: 'adamw'
RGM_batch_mode: 'Conserve_ratio'
RGM_erm_e: 1
RGM_rgm_e: 1
RGM_holdout_e: 1
RGM_detach_classifier: True
RGM_oracle: False
RGM_ensemble_pred: False
RGM_classifier_layers: 1
RGM_num_train_domains: -1
RGM_early_stopping: 'valid'
random_seed: 58
NN_clip_grad: 5
NN_reduce_lr_factor: 1.
learning_rate: 0.0005
coeff_lr_classifier: 3
lr_power_t: 0.5
nn_l2: 0.000001
RF_n_estimators: 200
GB_n_estimators: 200
GP_alpha: 0.3
GP_lengthscale: 1
